### ISSUE TITLE
Crashed on trying to put an enchanted trident in a utility slot.

### ISSUE THREAD

**Issue by Ynaught** [JamCoreModding/utility-belt#49]
The log reads as follows:

> ---- Minecraft Crash Report ----
> Time: 2024-06-30 18:36:53
> Description: Ticking entity
> 
> java.lang.IllegalArgumentException: Can't find id for 'Reference{ResourceKey[minecraft:enchantment / minecraft:mending]=Enchantment Mending}' in map net.minecraft.class_2378$1@702a4008
> 	at net.minecraft.class_2359.method_56158(class_2359.java:27)
> 	at net.minecraft.class_9135$16.method_56423(class_9135.java:484)
> 	at net.minecraft.class_9135$16.encode(class_9135.java:471)
> 	at net.minecraft.class_9135$13.method_59793(class_9135.java:406)
> 	at it.unimi.dsi.fastutil.objects.Object2IntMap.lambda$forEach$0(Object2IntMap.java:245)
> 	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$MapEntrySet.fastForEach(Object2IntOpenHashMap.java:1078)
> 	at it.unimi.dsi.fastutil.objects.Object2IntMap.forEach(Object2IntMap.java:247)
> 	at net.minecraft.class_9135$13.method_56418(class_9135.java:405)
> 	at net.minecraft.class_9135$13.encode(class_9135.java:401)
> 	at net.minecraft.class_9139$12.encode(class_9139.java:156)
> 	at net.minecraft.class_9326$1.method_57851(class_9326.java:123)
> 	at net.minecraft.class_9326$1.method_57850(class_9326.java:109)
> 	at net.minecraft.class_9326$1.encode(class_9326.java:59)
> 	at net.minecraft.class_1799$1.method_56100(class_1799.java:156)
> 	at net.minecraft.class_1799$1.encode(class_1799.java:132)
> 	at net.minecraft.class_9135$11.method_58006(class_9135.java:378)
> 	at net.minecraft.class_9135$11.encode(class_9135.java:363)
> 	at net.minecraft.class_9139$11.encode(class_9139.java:136)
> 	at net.minecraft.class_9139$8.encode(class_9139.java:81)
> 	at dev.architectury.impl.NetworkAggregator.collectPackets(NetworkAggregator.java:146)
> 	at dev.architectury.networking.NetworkManager.collectPackets(NetworkManager.java:137)
> 	at dev.architectury.networking.NetworkManager.sendToPlayer(NetworkManager.java:157)
> 	at io.github.jamalam360.utility_belt.server.ServerNetworking.sendInventoryToClient(ServerNetworking.java:27)
> 	at net.minecraft.class_3222.handler$geh000$utility_belt$utilitybelt$startPlayerTick(class_3222.java:12145)
> 	at net.minecraft.class_3222.method_5773(class_3222.java)
> 	at net.minecraft.class_3218.method_18762(class_3218.java:770)
> 	at net.minecraft.class_1937.method_18472(class_1937.java:498)
> 	at net.minecraft.class_3218.method_31420(class_3218.java:408)
> 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
> 	at net.minecraft.class_3218.method_18765(class_3218.java:372)
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
> 	at net.minecraft.class_1132.method_3748(class_1132.java:114)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Server thread
> Stacktrace:
> 	at net.minecraft.class_2359.method_56158(class_2359.java:27)
> 	at net.minecraft.class_9135$16.method_56423(class_9135.java:484)
> 	at net.minecraft.class_9135$16.encode(class_9135.java:471)
> 	at net.minecraft.class_9135$13.method_59793(class_9135.java:406)
> 	at it.unimi.dsi.fastutil.objects.Object2IntMap.lambda$forEach$0(Object2IntMap.java:245)
> 	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$MapEntrySet.fastForEach(Object2IntOpenHashMap.java:1078)
> 	at it.unimi.dsi.fastutil.objects.Object2IntMap.forEach(Object2IntMap.java:247)
> 	at net.minecraft.class_9135$13.method_56418(class_9135.java:405)
> 	at net.minecraft.class_9135$13.encode(class_9135.java:401)
> 	at net.minecraft.class_9139$12.encode(class_9139.java:156)
> 	at net.minecraft.class_9326$1.method_57851(class_9326.java:123)
> 	at net.minecraft.class_9326$1.method_57850(class_9326.java:109)
> 	at net.minecraft.class_9326$1.encode(class_9326.java:59)
> 	at net.minecraft.class_1799$1.method_56100(class_1799.java:156)
> 	at net.minecraft.class_1799$1.encode(class_1799.java:132)
> 	at net.minecraft.class_9135$11.method_58006(class_9135.java:378)
> 	at net.minecraft.class_9135$11.encode(class_9135.java:363)
> 	at net.minecraft.class_9139$11.encode(class_9139.java:136)
> 	at net.minecraft.class_9139$8.encode(class_9139.java:81)
> 	at dev.architectury.impl.NetworkAggregator.collectPackets(NetworkAggregator.java:146)
> 	at dev.architectury.networking.NetworkManager.collectPackets(NetworkManager.java:137)
> 	at dev.architectury.networking.NetworkManager.sendToPlayer(NetworkManager.java:157)
> 	at io.github.jamalam360.utility_belt.server.ServerNetworking.sendInventoryToClient(ServerNetworking.java:27)
> 	at net.minecraft.class_3222.handler$geh000$utility_belt$utilitybelt$startPlayerTick(class_3222.java:12145)
> 	at net.minecraft.class_3222.method_5773(class_3222.java)
> 	at net.minecraft.class_3218.method_18762(class_3218.java:770)
> 	at net.minecraft.class_1937.method_18472(class_1937.java:498)
> 	at net.minecraft.class_3218.method_31420(class_3218.java:408)
> 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
> 
> -- Entity being ticked --
> Details:
> 	Entity Type: minecraft:player (net.minecraft.class_3222)
> 	Entity ID: 616
> 	Entity Name: Noah_Dekka
> 	Entity's Exact location: -218292.95, 82.00, -1000383.39
> 	Entity's Block location: World: (-218293,82,-1000384), Section: (at 11,2,0 in -13644,5,-62524; chunk contains blocks -218304,-64,-1000384 to -218289,319,-1000369), Region: (-427,-1954; contains chunks -13664,-62528 to -13633,-62497, blocks -218624,-64,-1000448 to -218113,319,-999937)
> 	Entity's Momentum: 0.00, -0.08, 0.00
> 	Entity's Passengers: []
> 	Entity's Vehicle: null
> Stacktrace:
> 	at net.minecraft.class_1937.method_18472(class_1937.java:498)
> 	at net.minecraft.class_3218.method_31420(class_3218.java:408)
> 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
> 	at net.minecraft.class_3218.method_18765(class_3218.java:372)
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
> 	at net.minecraft.class_1132.method_3748(class_1132.java:114)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> 
> -- Affected level --
> Details:
> 	All players: 1 total; [class_3222['Noah_Dekka'/616, l='ServerLevel[1am]', x=-218292.95, y=82.00, z=-1000383.39]]
> 	Chunk stats: 2601
> 	Level dimension: minecraft:overworld
> 	Level spawn location: World: (16,63,1), Section: (at 0,15,1 in 1,3,0; chunk contains blocks 16,-64,0 to 31,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
> 	Level time: 5538657 game time, 7708616 day time
> 	Level name: 1am
> 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Commands: true
> 	Level weather: Rain time: 73090 (now: false), thunder time: 103991 (now: false)
> 	Known server brands: fabric
> 	Removed feature flags: 
> 	Level was modded: true
> 	Level storage version: 0x04ABD - Anvil
> 	Loaded entity count: 327
> Stacktrace:
> 	at net.minecraft.class_3218.method_8538(class_3218.java:1693)
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1024)
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
> 	at net.minecraft.class_1132.method_3748(class_1132.java:114)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.21
> 	Minecraft Version ID: 1.21
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 21.0.3, Microsoft
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
> 	Memory: 4082788728 bytes (3893 MiB) / 7616856064 bytes (7264 MiB) up to 8589934592 bytes (8192 MiB)
> 	CPUs: 16
> 	Processor Vendor: AuthenticAMD
> 	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
> 	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
> 	Microarchitecture: Zen 2
> 	Frequency (GHz): 3.59
> 	Number of physical packages: 1
> 	Number of physical CPUs: 8
> 	Number of logical CPUs: 16
> 	Graphics card #0 name: AMD Radeon RX 5700 XT
> 	Graphics card #0 vendor: Advanced Micro Devices, Inc.
> 	Graphics card #0 VRAM (MiB): 8176.00
> 	Graphics card #0 deviceId: VideoController1
> 	Graphics card #0 versionInfo: 31.0.21031.1005
> 	Memory slot #0 capacity (MiB): 16384.00
> 	Memory slot #0 clockSpeed (GHz): 3.20
> 	Memory slot #0 type: DDR4
> 	Memory slot #1 capacity (MiB): 16384.00
> 	Memory slot #1 clockSpeed (GHz): 3.20
> 	Memory slot #1 type: DDR4
> 	Virtual memory max (MiB): 52154.40
> 	Virtual memory used (MiB): 38515.27
> 	Swap memory total (MiB): 19456.00
> 	Swap memory used (MiB): 1086.22
> 	Space in storage for jna.tmpdir (MiB): available: 552401.50, total: 1953497.00
> 	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 552401.50, total: 1953497.00
> 	Space in storage for io.netty.native.workdir (MiB): available: 552401.50, total: 1953497.00
> 	Space in storage for java.io.tmpdir (MiB): available: 1585268.38, total: 1907082.00
> 	Space in storage for workdir (MiB): available: 552401.50, total: 1953497.00
> 	JVM Flags: 10 total; -Xmx8192M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
> 	Enabled Feature Flags: minecraft:bundle, minecraft:vanilla
> 	World Generation: Stable
> 	World Seed: -2243382515033090771
> 	Type: Integrated Server (map_client.txt)
> 	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
> 	Launched Version: 1.21

**Comment by Ynaught** [comment]
Turns out it might be any enchantment:

> java.lang.IllegalArgumentException: Can't find id for 'Reference{ResourceKey[minecraft:enchantment / minecraft:sweeping_edge]=Enchantment Sweeping Edge}' in map net.minecraft.class_2378$1@23043dc
> 	at net.minecraft.class_2359.method_56158(class_2359.java:27)
> 	at net.minecraft.class_9135$16.method_56423(class_9135.java:484)
> 	at net.minecraft.class_9135$16.encode(class_9135.java:471)
> 	at net.minecraft.class_9135$13.method_59793(class_9135.java:406)
> 	at it.unimi.dsi.fastutil.objects.Object2IntMap.lambda$forEach$0(Object2IntMap.java:245)
> 	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$MapEntrySet.fastForEach(Object2IntOpenHashMap.java:1078)
> 	at it.unimi.dsi.fastutil.objects.Object2IntMap.forEach(Object2IntMap.java:247)
> 	at net.minecraft.class_9135$13.method_56418(class_9135.java:405)
> 	at net.minecraft.class_9135$13.encode(class_9135.java:401)
> 	at net.minecraft.class_9139$12.encode(class_9139.java:156)
> 	at net.minecraft.class_9326$1.method_57851(class_9326.java:123)
> 	at net.minecraft.class_9326$1.method_57850(class_9326.java:109)
> 	at net.minecraft.class_9326$1.encode(class_9326.java:59)
> 	at net.minecraft.class_1799$1.method_56100(class_1799.java:156)
> 	at net.minecraft.class_1799$1.encode(class_1799.java:132)
> 	at net.minecraft.class_9135$11.method_58006(class_9135.java:378)
> 	at net.minecraft.class_9135$11.encode(class_9135.java:363)
> 	at net.minecraft.class_9139$11.encode(class_9139.java:136)
> 	at net.minecraft.class_9139$8.encode(class_9139.java:81)
> 	at dev.architectury.impl.NetworkAggregator.collectPackets(NetworkAggregator.java:146)
> 	at dev.architectury.networking.NetworkManager.collectPackets(NetworkManager.java:137)
> 	at dev.architectury.networking.NetworkManager.sendToPlayer(NetworkManager.java:157)
> 	at io.github.jamalam360.utility_belt.server.ServerNetworking.sendInventoryToClient(ServerNetworking.java:27)
> 	at net.minecraft.class_3222.handler$geh000$utility_belt$utilitybelt$startPlayerTick(class_3222.java:12145)
> 	at net.minecraft.class_3222.method_5773(class_3222.java)
> 	at net.minecraft.class_3218.method_18762(class_3218.java:770)
> 	at net.minecraft.class_1937.method_18472(class_1937.java:498)
> 	at net.minecraft.class_3218.method_31420(class_3218.java:408)
> 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
> 	at net.minecraft.class_3218.method_18765(class_3218.java:372)
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
> 	at net.minecraft.class_1132.method_3748(class_1132.java:114)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Server thread
> Stacktrace:
> 	at net.minecraft.class_2359.method_56158(class_2359.java:27)
> 	at net.minecraft.class_9135$16.method_56423(class_9135.java:484)
> 	at net.minecraft.class_9135$16.encode(class_9135.java:471)
> 	at net.minecraft.class_9135$13.method_59793(class_9135.java:406)
> 	at it.unimi.dsi.fastutil.objects.Object2IntMap.lambda$forEach$0(Object2IntMap.java:245)
> 	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$MapEntrySet.fastForEach(Object2IntOpenHashMap.java:1078)
> 	at it.unimi.dsi.fastutil.objects.Object2IntMap.forEach(Object2IntMap.java:247)
> 	at net.minecraft.class_9135$13.method_56418(class_9135.java:405)
> 	at net.minecraft.class_9135$13.encode(class_9135.java:401)
> 	at net.minecraft.class_9139$12.encode(class_9139.java:156)
> 	at net.minecraft.class_9326$1.method_57851(class_9326.java:123)
> 	at net.minecraft.class_9326$1.method_57850(class_9326.java:109)
> 	at net.minecraft.class_9326$1.encode(class_9326.java:59)
> 	at net.minecraft.class_1799$1.method_56100(class_1799.java:156)
> 	at net.minecraft.class_1799$1.encode(class_1799.java:132)
> 	at net.minecraft.class_9135$11.method_58006(class_9135.java:378)
> 	at net.minecraft.class_9135$11.encode(class_9135.java:363)
> 	at net.minecraft.class_9139$11.encode(class_9139.java:136)
> 	at net.minecraft.class_9139$8.encode(class_9139.java:81)
> 	at dev.architectury.impl.NetworkAggregator.collectPackets(NetworkAggregator.java:146)
> 	at dev.architectury.networking.NetworkManager.collectPackets(NetworkManager.java:137)
> 	at dev.architectury.networking.NetworkManager.sendToPlayer(NetworkManager.java:157)
> 	at io.github.jamalam360.utility_belt.server.ServerNetworking.sendInventoryToClient(ServerNetworking.java:27)
> 	at net.minecraft.class_3222.handler$geh000$utility_belt$utilitybelt$startPlayerTick(class_3222.java:12145)
> 	at net.minecraft.class_3222.method_5773(class_3222.java)
> 	at net.minecraft.class_3218.method_18762(class_3218.java:770)
> 	at net.minecraft.class_1937.method_18472(class_1937.java:498)
> 	at net.minecraft.class_3218.method_31420(class_3218.java:408)
> 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
> 
> -- Entity being ticked --
> Details:
> 	Entity Type: minecraft:player (net.minecraft.class_3222)
> 	Entity ID: 611
> 	Entity Name: Noah_Dekka
> 	Entity's Exact location: -218292.95, 82.00, -1000383.39
> 	Entity's Block location: World: (-218293,82,-1000384), Section: (at 11,2,0 in -13644,5,-62524; chunk contains blocks -218304,-64,-1000384 to -218289,319,-1000369), Region: (-427,-1954; contains chunks -13664,-62528 to -13633,-62497, blocks -218624,-64,-1000448 to -218113,319,-999937)
> 	Entity's Momentum: 0.00, -0.08, 0.00
> 	Entity's Passengers: []
> 	Entity's Vehicle: null
> Stacktrace:
> 	at net.minecraft.class_1937.method_18472(class_1937.java:498)
> 	at net.minecraft.class_3218.method_31420(class_3218.java:408)
> 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
> 	at net.minecraft.class_3218.method_18765(class_3218.java:372)
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
> 	at net.minecraft.class_1132.method_3748(class_1132.java:114)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> 
> -- Affected level --
> Details:
> 	All players: 1 total; [class_3222['Noah_Dekka'/611, l='ServerLevel[1am]', x=-218292.95, y=82.00, z=-1000383.39]]
> 	Chunk stats: 2601
> 	Level dimension: minecraft:overworld
> 	Level spawn location: World: (16,63,1), Section: (at 0,15,1 in 1,3,0; chunk contains blocks 16,-64,0 to 31,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
> 	Level time: 5539051 game time, 7709010 day time
> 	Level name: 1am
> 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Commands: true
> 	Level weather: Rain time: 72696 (now: false), thunder time: 103597 (now: false)
> 	Known server brands: fabric
> 	Removed feature flags: 
> 	Level was modded: true
> 	Level storage version: 0x04ABD - Anvil
> 	Loaded entity count: 330
> Stacktrace:
> 	at net.minecraft.class_3218.method_8538(class_3218.java:1693)
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1024)
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
> 	at net.minecraft.class_1132.method_3748(class_1132.java:114)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Jamalam360** [comment]
I'm struggling to reproduce this. Do you have any more information? And maybe versions of mods you are using please

**Comment by Ynaught** [comment]
mod"s" plural? If you asking for all the mods. . . it's a long list. I'll see what I can do, but it might I'll try this: I'll try to recreate the event and capture the footage and then when it crashes, get the mod list from the crash report.

**Comment by Jamalam360** [comment]
The verision of every mod should be near the top of latest.log
