### ISSUE TITLE
ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 4 caused by $utilitybelt$tryPlaceStackInBelt

### ISSUE THREAD

**Issue by alexweber** [JamCoreModding/utility-belt#55]
Confirm duplication is fixed, thanks!!  But now getting this and it's causing players to disconnect...  let me know if I can provide more info... not placing anything crazy into utility belts just vanilla items

```
[22:06:51] [Server thread/WARN]: Failed to handle packet for /IP-REDACTED:51488
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:652) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:268) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:401) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:176) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1032) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:299) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 4
        at java.base/java.util.Arrays$ArrayList.set(Arrays.java:4271) ~[?:?]
        at net.minecraft.class_2371.set(class_2371.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.class_1277.method_5447(class_1277.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.class_1661.handler$bnb000$utility_belt$utilitybelt$tryPlaceStackInBelt(class_1661.java:1867) ~[server-intermediary.jar:?]
        at net.minecraft.class_1661.method_7367(class_1661.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_1661.method_7394(class_1661.java:249) ~[server-intermediary.jar:?]
        at net.minecraft.class_1542.method_5694(class_1542.java:385) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_7341(class_1657.java:654) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:627) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2507) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:312) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:588) ~[server-intermediary.jar:?]
        ... 9 more
```

**Comment by Jamalam360** [comment]
Thanks for the report, should be resolved in 2.4.3
